server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:proddb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  h2:
    console:
      enabled: false

# =========================
# ACTUATOR
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# =========================
# SECURITY (Resource Server)
# =========================
spring.security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://dummy-issuer-for-prod
