sonar.projectKey=TU_ORG_TU_PROYECTO    # Project key de SonarCloud
sonar.organization=TU_ORG              # Organización de SonarCloud
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts

# Informe de cobertura generado por Angular
sonar.javascript.lcov.reportPaths=coverage/ag-prueba-front/lcov.info

sonar.sourceEncoding=UTF-8
